// This file is a Redux Toolkit slice for authentication. Its purpose is to globally store the user login state:
// 'isLoggedIn'-state (authentification), role  ("user" / "admin"), user-object, token (JWT), and modal state, actions (login, logout)

import { createSlice } from "@reduxjs/toolkit";

// defining initial state, which will be added to 'createSlice' function
const initialState = {
  isLoggedIn: false,
  role: null,
  user: null,
  token: null,
  modalType: null, // 'login' or 'signup'
};

// createSlice contains reducer-functions (reducers) which use Immer library to enable changing state in immutable way (no spread-operator needed)
const authSlice = createSlice({
  name: "auth",
  initialState,
  reducers: {
    login: (state, action) => {
      state.isLoggedIn = true;
      state.role = action.payload.role;
      state.user = action.payload.user;
      state.token = action.payload.token;
      state.modalType = null; // close Modal after login was successful
    },
    logout: (state, action) => {
      state.isLoggedIn = false;
      state.role = null;
      state.user = null;
      state.token = null;
    },
    restoreSession: (state, action) => {
      // Used to restore session from HttpOnly cookie on app load
      state.isLoggedIn = true;
      state.role = action.payload.role;
      state.user = action.payload.user;
      state.token = action.payload.token;
    },
    setToken: (state, action) => {
      state.token = action.payload;
    },
    openLoginModal: (state) => {
      state.modalType = "login";
    },
    openSignupModal: (state) => {
      state.modalType = "signup";
    },
    closeModal: (state) => {
      state.modalType = null;
    },
  },
});

// exporting actions:
export const {
  login,
  logout,
  restoreSession,
  setToken,
  openLoginModal,
  openSignupModal,
  closeModal,
} = authSlice.actions;

// exporting reducer-function, generated by createSlice:
export default authSlice.reducer;


///////////////////////////////////////************************************////////////////////////////////////////////////

/* Alternative version of this file, but in ZUSTAND instead of Redux Toolkit (just for reference, not used in this project):

import { create } from "zustand";

const useAuthStore = create((set) => ({
  // initial state
  isLoggedIn: false,
  role: null,
  user: null,
  token: null,
  modalType: null,

  // actions
  login: ({ role, user, token }) =>
    set({
      isLoggedIn: true,
      role,
      user,
      token,
      modalType: null, // close modal after login
    }),

  logout: () =>
    set({
      isLoggedIn: false,
      role: null,
      user: null,
      token: null,
      modalType: null,
    }),

  restoreSession: ({ role, user, token }) =>
    set({
      isLoggedIn: true,
      role,
      user,
      token,
    }),

  setToken: (token) =>
    set({
      token,
    }),

  openLoginModal: () =>
    set({
      modalType: "login",
    }),

  openSignupModal: () =>
    set({
      modalType: "signup",
    }),

  closeModal: () =>
    set({
      modalType: null,
    }),
}));

export default useAuthStore;

///////////////////////
// USAGE in JavaScript:

dispatch(login({
   role: "admin",
   user: userData,
   token: token
}));

///////////////////////
// in Zustand:

const login = useAuthStore((state) => state.login);

login({
   role: "admin",
   user: userData,
   token: token
});

//////////////////////
// What is NOT needed in Zustand:

dispatch()
useSelector()
reducer
action creator

*/
